# Generated by Django 5.1.6 on 2025-03-10 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0002_alter_team_options_team_goal_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
        migrations.RenameField(
            model_name='fixture',
            old_name='date',
            new_name='match_date',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='drawn',
            new_name='draws',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='lost',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='played',
            new_name='matches_played',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='won',
            new_name='wins',
        ),
        migrations.AddField(
            model_name='fixture',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fixture',
            name='played',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='league_management.team'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='league_management.team'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
