# Generated by Django 5.1.6 on 2025-03-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0003_remove_player_team_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_scored_against',
            field=models.IntegerField(default=0),
        ),
    ]
