# Generated by Django 5.1.6 on 2025-03-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0006_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='match_date',
            field=models.DateTimeField(),
        ),
    ]
