# Generated by Django 5.1.6 on 2025-03-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0007_alter_fixture_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='kickoff_time',
            field=models.TimeField(default='8:00:00'),
        ),
        migrations.AddField(
            model_name='fixture',
            name='stadium',
            field=models.CharField(default='Main Stadium', max_length=255),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='match_date',
            field=models.DateField(),
        ),
    ]
