# Generated by Django 5.1.6 on 2025-03-17 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_management', '0008_fixture_kickoff_time_fixture_stadium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='goals_scored',
        ),
        migrations.RemoveField(
            model_name='team',
            name='goals_scored_against',
        ),
        migrations.AlterField(
            model_name='fixture',
            name='kickoff_time',
            field=models.TimeField(default='08:00:00'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='match_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('assist', 'Assist'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card')], max_length=20)),
                ('timestamp', models.TimeField()),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='league_management.fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_management.player')),
            ],
        ),
    ]
